### ISSUE TITLE
How to connect the python helloworld with the C++ helloworld?

### ISSUE THREAD

**Issue by wuxianshen** [eclipse-cyclonedds/cyclonedds-python#139] opened 2022-08-26 03:32 UTC
I install cyclonedds through the following command under an anaconda envrionment:
pip install cyclonedds

The python helloworld example works fine.

When I try to connect the helloworlddata example with the python helloworld example, I change the python file to:

`@dataclass
class HelloWorldData(IdlStruct, typename="HelloWorldData_Msg"):
    userID: int
    message: str

def cdds_demo():
    dp = DomainParticipant()   
    tp = Topic(dp, "HelloWorldData_Msg", HelloWorldData)
    dr = DataReader(dp, tp)
    while True:
        samples = dr.read()
        if len(samples) == 0:
            continue
        sample = samples[0]
        print(sample.data)`

C++ publisher:
https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/examples/helloworld/publisher.c

And run the C++ publisher and this python file, but they do not act as I expected.
Is there any problems about the configuration?
I tried to modified the domain_id in dds_create_participant to 0, but nothing changed.

And, is it possible to use the command line tooling in Windows 10?

**Comment by thijsmie** [comment] 2022-08-26 08:43
Hi @wuxianshen,

The typename is not "HelloWorldData_Msg" but "HelloWorldData::Msg", with "::" being the namespace separator. You can also use "HelloWorldData.Msg" in python this will be automatically converted.

The command line tooling should be usable on windows, to be released in 0.10.2.

**Closed by thijsmie** 2022-08-26 08:43 UTC

**Comment by wuxianshen** [comment] 2022-08-26 13:24
Sorry to disturb again, but after change the typename, I still cannot connect C++ with python;


The C++ codes:
`
int main (int argc, char ** argv)
{
  dds_entity_t participant;
  dds_entity_t topic;
  dds_entity_t writer;
  dds_return_t rc;
  HelloWorldData_Msg msg;
  uint32_t status = 0;
  (void)argc;
  (void)argv;

  //int dds_domain = 0; //DDS_DOMAIN_DEFAULT
  int dds_domain = DDS_DOMAIN_DEFAULT;
  participant = dds_create_participant (dds_domain, NULL, NULL);
  if (participant < 0)
    DDS_FATAL("dds_create_participant: %s\n", dds_strretcode(-participant));

  topic = dds_create_topic (
    participant, &HelloWorldData_Msg_desc, "HelloWorldData_Msg", NULL, NULL);
  if (topic < 0)
    DDS_FATAL("dds_create_topic: %s\n", dds_strretcode(-topic));

  writer = dds_create_writer (participant, topic, NULL, NULL);
  if (writer < 0)
    DDS_FATAL("dds_create_writer: %s\n", dds_strretcode(-writer));
  msg.userID = 1;
  msg.message = "Hello World";

  printf ("=== [Publisher]  Writing : ");
  printf ("Message (%"PRId32", %s)\n", msg.userID, msg.message);
  fflush (stdout);

  rc = dds_write (writer, &msg);
  if (rc != DDS_RETCODE_OK)
    DDS_FATAL("dds_write: %s\n", dds_strretcode(-rc));

  rc = dds_delete (participant);
  if (rc != DDS_RETCODE_OK)
    DDS_FATAL("dds_delete: %s\n", dds_strretcode(-rc));

  return EXIT_SUCCESS;
}
`

The python code:
`
@dataclass
class HelloWorldData(IdlStruct, typename="HelloWorldData::Msg"):
    userID: int
    message: str

def cdds_demo():
    dp = DomainParticipant()
    tp = Topic(dp, "HelloWorldData_Msg", HelloWorldData)
    dr = DataReader(dp, tp)
    while True:
        samples = dr.read()
        if len(samples) == 0:
            continue
        sample = samples[0]
        print(f'Msg id {sample.userID}, content {sample.message}')
`

The C++ publisher and subscriber work fine;
Also, the python publisher and subscriber work fine;
But C++ publisher and python subscriber cannot connect.

Is there any other errors here?

The python-binding is installed with:
D:\Software\Anaconda3\envs\pycycdds\python.exe -m pip install git+https://github.com/eclipse-cyclonedds/cyclonedds-python

**Comment by eboasson** [comment] 2022-08-26 15:30
It is not working because there is still a type mismatch between the publisher and the subscriber, caused by two unrelated differences:
* The topic in the C code has a key, but in the Python code there is no key. You can annotate the Python data class to solve this.
* The Python `int` is mapped to a 64-bit integer (`long long` in OMG IDL) as the closest approximation of the Python integers. The C code however uses a 32-bit integer, so you need to use a different type for the `userID`.

You might want to give `cyclonedds typeof HelloWorldData_Msg` a try, it should show you the two different definitions.

To fix this, you need to import the `key` annotation and the `int32` type from the Cyclone DDS python packages:
```
from cyclonedds.idl.annotations import key
from cyclonedds.idl.types import int32

@dataclass
class HelloWorldData(IdlStruct, typename="HelloWorldData::Msg"):
    userID: int32
    key("userID")
    message: str
```

**Comment by wuxianshen** [comment] 2022-08-27 02:34
Thanks for your reply!

I have tried the codes in your reply, but still cannot connect C++ and python terminals.
The C++ publisher:

`#include "dds/dds.h"
#include "HelloWorldData.h"
#include <stdio.h>
#include <stdlib.h>

int main (int argc, char ** argv)
{
  dds_entity_t participant;
  dds_entity_t topic;
  dds_entity_t writer;
  dds_return_t rc;
  HelloWorldData_Msg msg;
  uint32_t status = 0;
  (void)argc;
  (void)argv;

  /* Create a Participant. */
  //int dds_domain = 0; //DDS_DOMAIN_DEFAULT
  int dds_domain = DDS_DOMAIN_DEFAULT;
  participant = dds_create_participant (dds_domain, NULL, NULL);
  if (participant < 0)
    DDS_FATAL("dds_create_participant: %s\n", dds_strretcode(-participant));

  /* Create a Topic. */
  topic = dds_create_topic (
    participant, &HelloWorldData_Msg_desc, "HelloWorldData_Msg", NULL, NULL);
  if (topic < 0)
    DDS_FATAL("dds_create_topic: %s\n", dds_strretcode(-topic));

  /* Create a Writer. */
  writer = dds_create_writer (participant, topic, NULL, NULL);
  if (writer < 0)
    DDS_FATAL("dds_create_writer: %s\n", dds_strretcode(-writer));

  printf("=== [Publisher]  Waiting for a reader to be discovered ...\n");
  fflush (stdout);

  rc = dds_set_status_mask(writer, DDS_PUBLICATION_MATCHED_STATUS);
  if (rc != DDS_RETCODE_OK)
    DDS_FATAL("dds_set_status_mask: %s\n", dds_strretcode(-rc));

  while(!(status & DDS_PUBLICATION_MATCHED_STATUS))
  {
    rc = dds_get_status_changes (writer, &status);
    if (rc != DDS_RETCODE_OK)
      DDS_FATAL("dds_get_status_changes: %s\n", dds_strretcode(-rc));

    // Polling sleep.
    dds_sleepfor (DDS_MSECS (20));
  }

  /* Create a message to write. */
  msg.userID = 1;
  msg.message = "Hello World";

  printf ("=== [Publisher]  Writing : ");
  printf ("Message (%"PRId32", %s)\n", msg.userID, msg.message);
  fflush (stdout);

  rc = dds_write (writer, &msg);
  if (rc != DDS_RETCODE_OK)
    DDS_FATAL("dds_write: %s\n", dds_strretcode(-rc));

  /* Deleting the participant will delete all its children recursively as well. */
  rc = dds_delete (participant);
  if (rc != DDS_RETCODE_OK)
    DDS_FATAL("dds_delete: %s\n", dds_strretcode(-rc));

  return EXIT_SUCCESS;
}
`

**Comment by wuxianshen** [comment] 2022-08-27 02:38
And I tried your suggestion about cyclonedds typeof, the C++ terminal outputs readable info, but the python terminal does not.

Start the C++ publisher, and run cyclonedds.exe typeof HelloWorldData_Msg:

![image](https://user-images.githubusercontent.com/21985528/187011042-d96aadb8-182e-4f9a-a480-cd4f11ad49be.png)


Start the python publisher or subscriber, and run cyclonedds.exe typeof HelloWorldData_Msg:

![image](https://user-images.githubusercontent.com/21985528/187011069-2e0af07f-b9fd-4f6f-96d9-bcaba44b26b5.png)

Detailed:
```
D:\Software\Anaconda3\envs\pycycdds\Scripts>cyclonedds.exe typeof HelloWorldData_Msg


   0:00:01 ---------------------------------------- Entities discovered: 1
Exception in thread Thread-1:
Traceback (most recent call last):
  File "D:\Software\Anaconda3\envs\pycycdds\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "D:\Software\Anaconda3\envs\pycycdds\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Software\Anaconda3\envs\pycycdds\lib\site-packages\cyclonedds\tools\cli\discovery\main.py", line 281, in type_discovery
    datatype, _ = dynamic.get_types_for_typeid(
  File "D:\Software\Anaconda3\envs\pycycdds\lib\site-packages\cyclonedds\dynamic.py", line 57, in get_types_for_typeid
    raise DDSException(ret, f"Could not fetch typeobject for {tid}")
cyclonedds.core.DDSException: [DDS_RETCODE_TIMEOUT] A timeout has occurred. Could not fetch typeobject for TypeIdentifier[Union](242, b'\xb1\xa3\xb1\xfb\x8b\x1a`Q`\x14)|;\x8a')
 🚨 No types could be discovered over XTypes
```

**Comment by eboasson** [comment] 2022-08-29 08:46
The code you have given is incomplete, we don't know what version you are using, nor what platform and so spamming us in this way is a bit annoying. Still, it should work and so we do try to help you.

Last Friday, when I commented on the annotation and the type, I did so after verifying that your python code (modified to use the correct imports and to *actually do something* rather than just defining a function) correctly receives the data from the unmodified "hello world" publisher in the repository. That works with the current `master` and the current release.

If `cyclonedds typeof HelloWoldData_Msg` says it can't find anything, then it looks like you're either using an old version for the C code, or you have built it without type discovery. Just to be sure, I re-tested with version 0.8.2 and it works fine. I'm not going to try your C code, it is not a compilable example as it is and you have the unmodified `HelloWorldPublisher` that I used (and that you obviously re-used) anyway.

FIY, here is the Python version I used:
```Python
from dataclasses import dataclass
from cyclonedds.domain import DomainParticipant
from cyclonedds.core import Qos, Policy
from cyclonedds.pub import DataWriter
from cyclonedds.sub import DataReader
from cyclonedds.topic import Topic
from cyclonedds.idl import IdlStruct
from cyclonedds.idl.annotations import key
from cyclonedds.idl.types import int32

@dataclass
class HelloWorldData(IdlStruct, typename="HelloWorldData::Msg"):
    userID: int32
    key("userID")
    message: str

dp = DomainParticipant()
tp = Topic(dp, "HelloWorldData_Msg", HelloWorldData)
dr = DataReader(dp, tp)
while True:
    samples = dr.take()
    if len(samples) == 0:
        continue
    sample = samples[0]
    print(f'Msg id {sample.userID}, content {sample.message}')
    break
```
And please do note that I removed the `def cdds_demo():` bit. The way you did it, there is no code to execute unless you explicitly call it in the REPL.
